### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/www#1017]
Selon le [DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale) la navigation doit ressembler à ca et se placer sous le header:

![Image](https://github.com/SocialGouv/www/assets/59922165/3d347a2b-1ab9-43cb-a2b6-d36ae17c6a85)

Les liens de la navigation:
- [ ] La Fabrique
- [ ] Startups d'État
- [ ] Documentation
- [ ] _Proposez vos idées_

**Comment by manon-silva** [comment]
**Menu :** 
Nos startups > Travail | Solidarités | Santé | Tout voir
La Fabrique > À propos | Notre offre | L'équipe
Proposer vos idées
Actualités
Recrutement
