### ISSUE TITLE
redirection domaines

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/www#598]
Rediriger incubateur.social.gouv.Fr et www.incubateur.social.gouv.Fr vers https://www.fabrique.social.gouv.fr/

**Comment by douglasduteil** [comment]
@gary-van-woerkens ?

**Comment by douglasduteil** [comment]
@igorrenquin ?

**Comment by igorrenquin** [comment]
Ce n'est pas le même visuel sur le site renvoyé par l'url fabrique.social.gouv.fr.
C'est normal?

**Comment by douglasduteil** [comment]
> C'est normal?

https://www.fabrique.social.gouv.fr est plus a jour que https://incubateur.social.gouv.fr oui
